### ISSUE TITLE
lambda crash

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#286] opened 2015-07-12 00:51 UTC
would be cool if lambda returned the last element, but this crashes for me

<pre><code>
----------begin_max5_patcher----------
599.3oc0V0zaiBCD8L7q.4SIRTBluBYkp5sdduuoZkAbSbWvl0XhR1p9eegw
PKoMoklFkU6kwxisG+l2yy.OZZfRDaoUHquY8CKCiGMML.WsNL5lafJHaSyI
Uv1PohhBJWgr0qonaUZ+RR0ZZ0M8KTo1kSgU58vqKX7bpBhCtyYIQktlwW8S
IMUowQf6bGWaKrue6P3hVqmqiq0cuDHQspORtcdYYvsIRd3JbLp02SllsF6Q
lYI0Jkfeb7WJoUMYNQwD7Av0WiPrab6famYHXGUVu.NI1K.R2msGIowGHoC5
ApdepckTcnQID9Jj0cm.mHbxXUk4jcuQumsowtDkSJRxHSH1VkRwJ7DxzoKQ
1K4y9cyxd8mJmwoohZNbTuNm2K3p6IozghXquJ1e.eXOG2Of5ifmHd3vy.06
4i0AC39f3OE2GNjeRE4BoNzPH2y7bPeiJcpJDcaozIUjQa23AjoqeeY5ZKRY
Y9tIy1zj7SuLJFNz+bTrDsXnhEcTEy6.JVzQTLWGbbr8qFdWc61577uSR+Es
oo3dyNI87i5BMVJxOB+Uan3eIZnbFdSEBIGdt2W5MUGgsea.+OEi4+eSW.x+
nxesTEeVTptxebzIT9Gbgq9gyCr5q9YKH8Z8uu3VIpko8WQe+JqWfQFsRw3.
8NbSg6so0rrLJenZ0T6QRxo.O3dvmYiFOAiAOQWN73OB7DbwfyXXG+SDM52R
MUsanxptPB.ookvC5GxysgoLtdJDQjjtg0u+PvCQ1TZoZpqpk5OxrMV+YQTQ
SiDIulAUhls27Sl+E.uXTmC
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment] 2016-08-31 05:26
fixed. duplicate of #292 and #314

**Closed by maccallum** 2016-08-31 05:26 UTC
Labels: 1.2 Release Contingency, bug
