### ISSUE TITLE
o.expr.codebox number literals support broken

### ISSUE THREAD

**Issue by ilzxc** [CNMAT/CNMAT-odot#293] opened 2015-07-16 05:54 UTC
It seems that all number literals are read as `int32` -- which means you can not bind the maximum `uint32` using a literal...

<pre><code>
----------begin_max5_patcher----------
444.3oc4TEqSCCCDcN4qvxS.JTRbbaZQhUlYGgPtItfKo1QNNUAp5+NNmSaR
QsPTECHwxIcmO+tme9Yuw2COWUyKwnaQOh771364AkZJ30l6gWwpSyYkPaX0
nLQYQN6cbfaUCu1.qbSsMRhnIzowSnI6VWVsRUYx4FX+QsUKXlzWExWdVySM
t4SFGNJL.kPahQtjXaB5o18HxbLX9xqiB2AuCay6EbGJX799aXVpJWocqDA3
1OruyEJoYAKEfHrWsRwGPsHxnvtiiPt+zzTaqueSHXvBHutPOJUkwaZ7Hp3c
nJgzDStfRlQmMIwFu73pI4GUSBAhgIfZRNtZN8jh48U44OvReiavAGjcJQFF
ZW3LE4BMujKMLiPI6clngS.PoGLk8C3W3p4a81cWGmg2dvV6w+Gb1ceSbI5J
D4Lb2C1bG+WybeRcF.CmKje8GYP.Zpen3Wppzo6NLsuiQcTJiWZDR3MTudZ9
4rWSuJxx3x9r19DfMOmCBX3QcACkNwCfNiOS13zJVQwZttrERfHVK4R28UR.
jJjtT.QrluVrqeJTgoslKi0YUoAxiqmNA61p0HqkUh16I6j25+YD9mZP
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment] 2015-07-16 17:23
This is by design—we made the decision at one point that the default should conform to the OSC spec. The solution to this is to support suffix types like C. Please close this and open a new one reminding us that the syntax of the language needs to support suffix type annotations.

**Comment by ilzxc** [comment] 2015-07-16 18:19
This has pretty deep implications -- thanks for the quick response.

**Closed** 2015-07-16 18:21 UTC
