### ISSUE TITLE
assign_to_index() can't take dynamic address in "lambda()"

### ISSUE THREAD

**Issue by kulpajj** [CNMAT/CNMAT-odot#344] opened 2017-08-10 18:43 UTC
seems to be that assign_to_index() can't take a dynamic address in a "lambda()", so you have to hardcode the address you want to manipulate in any "lambda()"

**Comment by ramagottfried** [comment] 2017-08-10 19:07
probably the issue is that you need to initialize your list before you can assign_to_index?  here's an example in a lambda, using a temporary address and then assigning to the dynamic name.

<pre><code>
----------begin_max5_patcher----------
864.3oc6Vs0aZCCE9Y3WwQgGFr41RRfBTo85dbZuWPUljCE24XmE6zBqZ+2m
uQ3x.IZEpOMTjS7we9b2elWa2JZtbEphf6f6gVsdscqVNQVAsByaEUPWkwoJ
GrH404LUImtNh3WUiqztUtYgTdSeqp5SfS9LiLU3PFGPFSfDBjRfADXHAtk.
iHvXBLoAYR.YhCystUis6zHH1HI1HJdbC7z.7TG1IAbCsXL5vZNydRFMaS.v
YBLSVKbQwffPQcgrVyQsKpiCRWHE5EzLzJqePlGldcI5SiQQvrvRkUnBEZpl
IEOTgYZOha6O5Zi+MXh6U+vPytrIzLIWV4QGaWeugFjrbeIY9SWkFsiKpX+1
4LwIW2ea7vDGFNkTc1Rl3wi4ao1WoCFXeMZn0n187m1ssCjytYAWUVcclLGs
.OrioCnWxTPtDUluPPQKPqHwiv7ZMTHqPHSVXSiJLepXpnfV1cp..NsXdNs6
8LaUG.vM.2nwhR3qfXAiy6ZZQ52a2k2rY6uFEjuJnBnQC2eOXDCylYTk8iOC
LXCjdDfpve00jU3n3Q8xttsz6pXnmGSvjFXJ1ihtvT+AioQegQBd3ddUNZJK
XPMjlo4qEzBV12MoDmh2Z3Ty7dGs4MdzQ6dSdKcueqly+AM6mnNhr2ryrqdb
x4zT2eWPmrodvksodrumdn6bTxfIu6l5+y.dtLfuKtrjKTYevXOU13O.prSQ
LENj2AVhU3mT.EBGrAyHFns14rtgxYWBic3I5.ywEVFQOwhMT0xGXhbbErVV
CBDyAsDXBllQ4lzliSkyT5MJPwDYH7h4gJzVrdUsUOuvzKOvEIfTf.RUqazh
jWaO6CFpaiNpUFWBrrWxJZ0Zflma4qsr0d7mzgNIccSDavKbAWFUDbVeHZb1
ylS+ffrq2tDK0Nogeu2aif28UGfJxgELAkyWui6YixMovP13t8uS3YJu9.N9
ic2PGPVZyzN8mwQSRnt7heqQxGxsFuqK.hunLAd9+gwd9fwGxD3b.Wp4f+Pr
SgV46SOnj0UYaR.gqqfsgQNpzlVCa8aGLodLGk.5bsS7YXmj+wN9viVV9LVo
Bfclvvc8jur3ZDhLoT+zT2zJ7Y1F7CcRnUl7q1jbqqbtUzpa82TGUXXGqD0L
W4ns0x+o8egy.Wh7
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment] 2018-04-18 20:54
@kulpajj can this issue be closed?

**Comment by kulpajj** [comment] 2018-04-18 20:56
sure this one was addressed.  Thanks.

**Closed** 2018-04-19 04:26 UTC
